version: '3.9'

services:
    mongo:
        image: mongo
        container_name: mongo
        restart: always
        hostname: mongodb
        ports:
            - 27017:27017
        volumes:
            - ./bot/mongo/data:/data/db
            - ./bot/mongo/initdb.d:/docker-entrypoint-initdb.d
        environment:
            MONGO_INITDB_DATABASE: applications-bot
        healthcheck:
            test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
            interval: 5s
            timeout: 10s
            retries: 3
            start_period: 5s
    bot:
        depends_on:
            mongo:
                condition: service_healthy
        build:
            context: ./bot/
            dockerfile: Dockerfile
        container_name: applications-bot
        stop_signal: SIGINT
        restart: on-failure
        volumes: 
            - ./bot/config:/app/applications-bot/bot/config
            - ./bot/gibberish:/app/applications-bot/bot/gibberish
        env_file: ./bot/.env
        environment:
            MONGODB_URI: mongodb://mongo:27017/applications-bot